image: php:7.1-cli

pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y git unzip libxml2-dev
          - echo "memory_limit=512M" >> /usr/local/etc/php/php.ini
          - php -r "readfile('https://getcomposer.org/installer');" | php
          - php composer.phar config http-basic.repo.magento.com $MAGE_USER $MAGE_PASS
          - php composer.phar global require hirak/prestissimo
          - php composer.phar install --prefer-dist
          - ./vendor/bin/grumphp run
